### PR TITLE
Feature/deseng76 77

### PR DESCRIPTION
**Pull request by Baelx**
- Increase project tabs font size
- remove partner first nation from project page

### CODE REVIEW

**Review by ShawnTurple — APPROVED** [review]
keep noticing that the linter and test automatic script keep failing. Are you still working on getting this normalized, or should those issues be fixed?

**Comment by Baelx** [comment]
>
@ShawnTurple  

Thanks for the review. When the tests were originally put in place, I wrote brief note about this in the PR notes. For now, we have the automated checks in place but correcting all the failed tests will be a bigger chunk of work to come later. 

The checks won't be blocking until we've done that.

**Review by CR-gbc — APPROVED** [review]
no need to assign to me, just add me to reviewers 😆

**Comment by Baelx** [comment]
> no need to assign to me, just add me to reviewers 😆

@CR-gbc  Whoops! I meant to put you all as reviewers

**Pull request merged**
